const allData = [
  [`Recent Repositories`, `最近仓库`],
  [`Search or jump to…`, `搜索并跳转至...`],
  [`Issues`, `问题`],
  [`Pull`, `合并`],
  [`request`, `请求`],
  [`s`, ``],
  [`Marketplace`, `市场`],
  [`Explore`, `探索`],
  [`Following`, `关注者`],
  [`Find a repository…`, `查找仓库`],
  [`Latest changes`, `最新变化`],
  [`hours ago`, `小时前`],
  [`days ago`, `天前`],
  [`New`, `新建`],
  [`Explore repositories`, `探索存储库`],
  [`Explore more →`, `探索更多 →`],
  [`Set status`, `设置状态`],
  [`Your profile`, `个人信息`],
  [`Your repositories`, `个人仓库`],
  [`Your codespaces`, `你的 codespaces`],
  [`Your projects`, `你的项目`],
  [`Signed in as`, `登陆账户为`],
  [`Feature preview`, `功能预览`],
  [`Upgrade`, `升级`],
  [`Try Enterprise`, `尝试企业版`],
  [`Help`, `帮助`],
  [`Settings`, `设置`],
  [`Sign out`, `退出`],
  [`Overview`, `概述`],
  [`Repositories`, `仓库`],
  [`Projects`, `项目`],
  [`Packages`, `包`],
  [`Popular repositories`, `流行的仓库`],
  [`Edit profile`, `编辑个人信息`],
  [`followers`, ` 被关注`],
  [`following`, ` 关注`],
  [`Public`, `公开`],
  [`Customize your pins`, `定义你的置顶项目`],
  [`Contribution settings`, `贡献设置`],
  [`Pinned`, `置顶`],
  [`Learn how we count contributions`, `了解我们如何计算贡献`],
  [`Code review`, `代码评审`],
  [`Pull requests`, `合并请求`],
  [`Commits`, `提交`],
  [`Contribution activity`, `贡献活动`],
  [`Show more activity`, `显示更多活动`],
  [`Code`, `代码`],
  [`Go to file`, `转至文件`],
  [`Add file`, `添加文件`],
  [`About`, `关于`],
  [`Pin`, `置顶`],
  [`Pin this repository to your profile`, `置顶这个项目到你的个人信息`],
  [`New repository`, `新建仓库`],
  [`Import repository`, `导入仓库`],
  [`New organization`, `新建组织`],
  [`Create a new release`, `创建一个新的版本`],
  [`Publish your first package`, `发布你的第一个包`],
  [`Releases`, `发布`],
  [`Packages `, `包`],
  [`No packages published`, `没有发布任何软件包`],
  [`Languages`, `语言`],
  [`Show more`, `显示更多`],
  [`Recent activity`, `最新动态`],
  [
    `When you take actions across GitHub, we’ll provide links to that activity here.`,
    `当你在 GitHub 上采取行动时，我们会在这里提供该活动的链接。`,
  ],
  [`More`, `更多`],
  [`Subscribe to your news feed`, `订阅你的 feed`],
  [`Blog`, `博客`],
  [`Shop`, `商店`],
  [`Contact GitHub`, `联系 Github`],
  [`Pricing`, `定价`],
  [`Training`, `培训`],
  [`Status`, `状态`],
  [`Security`, `安全`],
  [`Terms`, `团队`],
  [`Privacy`, `隐私`],
  [`Docs`, `文档`],
  [`New project`, `新建项目`],
  [`Activity  overview`, `活动概览`],
  [`Projects`, `项目`],
  [`Security`, `安全`],
  [`Insights`, `统计`],
  [`Create new file`, `创建新的文件`],
  [`Upload files`, `上传文件`],
  [`Code`, `代码`],
  [`Local`, `本地`],
  [`Clone`, `克隆`],
  [`Open with GitHub Desktop`, `在 Github 桌面程序中打开`],
  [`Download ZIP`, `下载压缩包`],
  [`New codespace`, `新建 codespace`],
  [`Less`, `更少`],
  [`Select type`, `选择类型`],
  [`Type`, `类型`],
  [`Language`, `语言`],
  [`Sort`, `排序`],
  [`Private`, `私有`],
  [`Select language`, `选择语言`],
  [`Select order`, `选择顺序`],
  [`Last updated`, `最近更新`],
  [`Create a new repository`, `创建一个新的仓库`],
  [`Owner`, `拥有者`],
  [`Repository name`, `仓库名字`],
  [`Description`, `描述`],
  [`(optional)`, `(可选)`],
  [
    `Anyone on the internet can see this repository. You choose who can commit.`,
    `互联网上的任何人都可以看到这个存储库。你选择谁能够提交。`,
  ],
  [
    `You choose who can see and commit to this repository.`,
    `你可以选择谁可以看到和提交这个版本库。`,
  ],
  [
    `A repository contains all project files, including the revision history. Already have a project repository elsewhere?`,
    `一个仓库包含所有项目文件，包括修订历史。在其他地方已经有一个项目库了？`,
  ],
  [`Import a repository.`, `导入仓库`],
  [
    `Skip this step if you’re importing an existing repository.`,
    `如果你要导入一个已有的版本库，请跳过这一步。`,
  ],
  [
    `Choose which files not to track from a list of templates.`,
    `从一个模板列表中选择哪些文件不需要跟踪。`,
  ],
  [
    `This is where you can write a long description for your project.`,
    `在这里，你可以为你的项目写一个长的描述。`,
  ],
  [
    `A license tells others what they can and can't do with your code.`,
    `许可证告诉别人他们可以和不可以用你的代码做什么。`,
  ],
  [
    `You are creating a public repository in your personal account.`,
    `你正在你的个人账户中创建一个公共库。`,
  ],
  [`Initialize this repository with:`, `用以下方式初始化这个存储库：`],
  [`Create repository`, `创建仓库`],
  [
    `Great repository names are short and memorable. Need inspiration? How about`,
    `伟大的仓库名称是简短而令人难忘的。需要灵感吗？比如 `,
  ],
  [`Your personal account`, `你的个人账户`],
  [`Public profile`, `公开资料`],
  [`Name`, `名字`],
  [`Change username`, `修改用户名`],
  [`Account`, `账户`],
  [`Export account data`, `导出账户数据`],
  [`Appearance`, `外观`],
  [`Accessibility`, `无障碍设施`],
  [`Notifications`, `通知`],
  [`Access`, `访问`],
  [`Personal billing`, `个人帐单`],
  [`Emails`, `邮件`],
  [`Billing and plans`, `账单和计划`],
  [
    `This is a list of SSH keys associated with your account. Remove any keys that you do not recognize.`,
    `这是与你的账户相关的 SSH 密钥的列表，删除任何你不认识的密钥`,
  ],
  [`Organizations`, `组织`],
  [`You are not a member of any organizations.`, `你不是任何组织的成员  `],
  [`Archives`, `归档`],
  [`Security log`, `安全日志`],
  [`Sponsorship log`, `赞助日志`],
  [`No sponsorship activity in this time period`, `这段时间内没有赞助活动`],
  [`Sign in to GitHub`, `登录到 Github`],
  [`Username or email address`, `用户名或邮箱`],
  [`Password`, `密码`],
  [`Sign in`, `登录`],
  [`New to GitHub?`, `刚来 Github？`],
  [`Create an account`, `创建一个账户`],
  [`Forgot password?`, `忘记密码？`],
  [`Create an account`, ``],
  [
    `Label issues and pull requests for new contributors`,
    `为新的贡献者标记问题和合并请求`,
  ],
  [`Filters`, `过滤`],
  [`New Issue`, `新问题`],
  [`There aren’t any open issues.`, `没有任何公开的问题。`],
  [`Signing in…`, `登录中...`],
  [`Edit repository details`, `编辑仓库详情信息`],
  [`Website`, `网站`],
  [`Cancer`, `取消`],
  [`Save changes`, `保存修改`],
  [`Protect this branch`, `保护这个分支`],
  [`Get started with GitHub Actions`, `开始使用 Github Actions`],
  [
    `Build, test, and deploy your code. Make code reviews, branch management, and issue triaging work the way you want. Select a workflow to get started.`,
    `构建、测试和部署你的代码。使代码审查、分支管理和问题分流以你想要的方式进行。选择一个工作流程来开始。`,
  ],
  [`Browse all categories`, `浏览所有类型`],
  [`Automation`, `自动化`],
  [`Deployment`, `部署`],
  [`Continuous integration`, `持续集成`],
  [`Reporting`, `报告`],
  [`General`, `常规`],
  [`Public email`, `公开的邮箱`],
  [`Bio`, `个人简历`],
  [`URL`, `网站`],
  [`Twitter username`, `Twitter 用户名`],
  [`Company`, `公司`],
  [`Location`, `地址`],
  [`Contributions & Activity`, `贡献和活动`],
  [`Successor settings`, `继承人设置`],
  [`You have not designated a successor.`, `你还没有指定继承人`],
  [`Delete account`, `删除账户`],
  [
    `Once you delete your account, there is no going back. Please be certain.`,
    `一旦你删除了你的账户，就不能够找回了，请慎重`,
  ],
  [`Display current local time`, `显示当前的本地时间`],
  [`Keyboard shortcuts`, `快捷键`],
  [`Subscriptions`, `订阅`],
  [`Verified domains`, `验证的域名`],
  [`There are no verified domains.`, `没有经过验证的域名`],
  [`Password and authentication`, `密码和身份验证`],
  [`Change password`, `修改密码`],
  [`Old password`, `旧密码`],
  [`New password`, `新密码`],
  [`Confirm new password`, `确认新的密码`],
  [`Two-factor authentication`, `两步验证`],
  [`Confirm new password`, `确认新的密码`],
  [`Confirm access`, `确认访问`],
  [`Confirm`, `确认`],
  [`Who has access`, `谁有权限`],
  [`Code and automation`, `代码和自动化`],
  [`Default branch`, `默认分支`],
  [`Branch protection rules`, `分支保护规则`],
  [`Protected tags`, `保护标签`],
  [`Environments`, `环境变量`],
  [`Code security and analysis`, `代码安全性和分析`],
  [`Integrations`, `集成`],
  [`Email notifications`, `邮件通知`],
  [`Collaborators`, `合作者`],
  [`Contributors`, `贡献者`],
  [`Community Standards`, `社区标准`],
  [`Traffic`, `流量`],
  [`Code frequency`, `代码频率`],
  [`Dependency graph`, `依赖图`],
  [`Contributors`, `贡献者`],
  [`You can`, `你可以`],
  [`@mention`, `@`],
  [
    `other users and organizations to link to them.`,
    `其他用户和组织来链接它们`,
  ],
  [`Save`, `保存`],
  [`Cancel`, `取消`],
  [`Welcome to the all-new projects`, `欢迎来到全新的项目`],
  [`No open projects`, `没有开放的项目`],
  [`Add a bio`, `添加个人简介`],
  [`Loading more...`, `正在加载中`],
  [
    `Your popular repositories will now be shown instead of your pins.`,
    `你的热门仓库现在将显示，而不是你的置顶`,
  ],
  [`Unpin`, `不置顶`],
  [`Your pins have been updated.`, `你的置顶已经更新了`],
  [`Advanced search`, `高级搜索`],
  [`Branches`, `分支`],
  [`Social Preview`, `社交预览`],
  [
    `Upload an image to customize your repository’s social media preview.`,
    `上传图片来定制你仓库的社交媒体预览`,
  ],
  [`Pull Requests`, `合并请求`],
  [`Danger Zone`, `危险区`],
  [`Change repository visibility`, `修改仓库的可见性`],
  [`Transfer ownership`, `转让所有权`],
  [`This repository is currently public.`, `这个仓库当前是公开的`],
  [`Archive this repository`, `归档这个仓库`],
  [
    `Mark this repository as archived and read-only.`,
    `将此版本库标记为归档和只读`,
  ],
  [`Delete this repository`, `删除这个仓库`],
  [
    `Once you delete a repository, there is no going back. Please be certain.`,
    `一旦你删除了这个仓库，就不能够撤回了，请确认`,
  ],
  [`Are you absolutely sure?`, `你真的确定吗？`],
  [`Change visibility`, `修改可见性`],
  [`Change to private`, `修改为私有`],
  [`Transfer`, `转移`],
  [`Edit status`, `编辑状态`],
  [`Busy`, `忙`],
  [`Clear status`, `清除状态`],
  [`Never`, `从不`],
  [`Your main branch isn't protected`, `你的 main 分支不是受保护的`],
  [
    `Protect this branch from force pushing or deletion, or require status checks before merging.`,
    `保护这个分支不被强行推送或删减，或要求在合并前进行状态检查 `,
  ],
  [`Learn more`, `学习更多`],
  [`Branch protection rule`, `分支保护规则`],
  [`Protect your most important branches`, `保护你最重要的分支`],
  [`Achievements`, `成就`],
  [`Send feedback`, `发送反馈`],
  [`Choose a license`, `选择许可证`],
  [`Learn more.`, `学习更多`],
  [`Import your project to GitHub`, `导入你得项目到 Github`],
  [`Inbox`, `收件箱`],
  [`Prev`, `上页`],
  [`Next`, `下页`],
  [`Saved`, `保存`],
  [`Done`, `完成`],
  [`Manage notifications`, `管理通知`],
  [`See more`, `查看更多`],
  [`Include in the home page`, `显示在页面上`],
  [`Discussions`, `讨论`],
  [`Users`, `用户`],
  [`This repository is currently private.`, `这个仓库当前是私有的`],
  [`Lists`, `列表`],
  [`Create list`, `创建列表`],
  [`Pushes`, `推送`],
  [
    `Limit how many branches and tags can be updated in a single push`,
    `限制一次推送中可以更新多少个分支和标签`,
  ],
  [`I want to make this repository private`, `我想要让这个仓库变为私有`],
  [`I have read and understand these effects`, `我已经阅读并理解了这些影响`],
  [`New issue`, `新建问题`],
  [`Labels`, `标签`],
  [`New milestone`, `新建里程碑`],
  [`Milestones`, `里程碑`],
  [`You haven’t created any Milestones.`, `你还没有创建任何里程碑。`],
  [`Edit`, `编辑`],
  [`Delete`, `删除`],
  [`Close`, `关闭`],
  [`Success`, `完成`],
  [`Dashboard`, `仪表盘`],
  [`to search`, `搜索`],
  [`Create your first project`, `创建您的第一个项目`],
  [
  `Ready to start building? Create a repository for a new idea or bring over an existing repository to keep contributing to it.`,
  `准备好开始构建了吗？为新的想法创建一个存储库，或导入一个存储库以继续为它做出贡献。`,
  ],
  [`Filter`, `筛选`],
  [`Events`, `活动`],
  [`Activity you want to see on your feed`, `您希望在推送中看到的活动`],
  [`Stars`, `星`],
  [`main`, `主干`],
  [`Default`, `默认值`],
  [`Tags`, `标签`],
  [`Watch`, `查看`],
  [`Fork`, `复刻`],
  [`Starred`, `标星`],
  [`Switch branches/tags`, `查看所有分支/标签`],
  [`Profile picture`, `简介图片`],
  [`SSH and GPG keys`, `SSH和GPG密钥`],
  [`Cancel changes`, `取消更改`],
  [`Commit changes...`, `提交更改...`],
  [`New discussion`, `新建讨论`],
  [`Discussions`, `讨论`],
  [`Announcements`, `公告`],
  [`Answered`, `已回答`],
  [`Unanswered`, `未回答`],
  [`Mark as answer`, `标记为答案`],
  [`Unmark as answer`, `取消答案标记`],
  [`Upvote`, `赞同`],
  [`Downvote`, `反对`],
  [`Lock conversation`, `锁定对话`],
  [`Unlock conversation`, `解锁对话`],
  [`Transfer issue`, `转移问题`],
  [`Create pull request`, `创建拉取请求`],
  [`Compare & pull request`, `比较并创建拉取请求`],
  [`Compare changes`, `比较更改`],
  [`Conversation`, `对话`],
  [`Files changed`, `已更改文件`],
  [`Review changes`, `审查更改`],
  [`Approve`, `批准`],
  [`Request changes`, `请求更改`],
  [`Submit review`, `提交审查`],
  [`Start a review`, `开始审查`],
  [`Finish your review`, `完成审查`],
  [`Add single comment`, `添加单条评论`],
  [`Viewed`, `已查看`],
  [`Hide resolved`, `隐藏已解决`],
  [`Resolve conversation`, `解决对话`],
  [`Unresolve conversation`, `取消解决对话`],
  [`Mark as resolved`, `标记为已解决`],
  [`Ready for review`, `准备好审查`],
  [`Convert to draft`, `转换为草稿`],
  [`Merge pull request`, `合并拉取请求`],
  [`Squash and merge`, `压缩并合并`],
  [`Rebase and merge`, `变基并合并`],
  [`Auto-merge`, `自动合并`],
  [`Enable auto-merge`, `启用自动合并`],
  [`Delete branch`, `删除分支`],
  [`Update branch`, `更新分支`],
  [`This branch is out-of-date`, `此分支已落后`],
  [`Conflicts that must be resolved`, `必须解决的冲突`],
  [`Resolve conflicts`, `解决冲突`],
  [`Actions`, `操作`],
  [`Workflows`, `工作流`],
  [`Artifacts`, `制品`],
  [`Runners`, `运行器`],
  [`Self-hosted runners`, `自托管运行器`],
  [`New workflow`, `新建工作流`],
  [`Run workflow`, `运行工作流`],
  [`Re-run jobs`, `重新运行作业`],
  [`Re-run failed jobs`, `重新运行失败作业`],
  [`Cancel workflow`, `取消工作流`],
  [`Queued`, `排队中`],
  [`In progress`, `进行中`],
  [`Completed`, `已完成`],
  [`Skipped`, `已跳过`],
  [`Timed out`, `已超时`],
  [`Cancelled`, `已取消`],
  [`Workflow file`, `工作流文件`],
  [`Event`, `事件`],
  [`Actor`, `执行者`],
  [`Jobs`, `作业`],
  [`Step summary`, `步骤摘要`],
  [`Annotations`, `注解`],
  [`Secrets and variables`, `机密和变量`],
  [`Repository secrets`, `仓库机密`],
  [`Organization secrets`, `组织机密`],
  [`Actions secrets and variables`, `Actions 机密和变量`],
  [`Variables`, `变量`],
  [`Security overview`, `安全总览`],
  [`Dependabot alerts`, `Dependabot 警报`],
  [`Code scanning`, `代码扫描`],
  [`Secret scanning`, `机密扫描`],
  [`Dependabot security updates`, `Dependabot 安全更新`],
  [`Private vulnerability reporting`, `私密漏洞报告`],
  [`Advisories`, `安全通告`],
  [`CodeQL`, `CodeQL`],
  [`Copilot`, `Copilot`],
  [`GitHub Copilot`, `GitHub Copilot`],
  [`Copilot Chat`, `Copilot 聊天`],
  [`Ask Copilot`, `询问 Copilot`],
  [`Use this template`, `使用此模板`],
  [`Template repository`, `模板仓库`],
  [`Generate`, `生成`],
  [`Generate new repository`, `生成新仓库`],
  [`Use template`, `使用模板`],
  [`Code owners`, `代码所有者`],
  [`Blame`, `追溯`],
  [`Raw`, `原始`],
  [`Permalink`, `永久链接`],
  [`History`, `历史`],
  [`View file`, `查看文件`],
  [`Edit this file`, `编辑此文件`],
  [`Delete this file`, `删除此文件`],
  [`Open file`, `打开文件`],
  [`Copy path`, `复制路径`],
  [`Copy permalink`, `复制永久链接`],
  [`View all files`, `查看所有文件`],
  [`Latest`, `最新`],
  [`Pre-release`, `预发布`],
  [`Draft release`, `草稿版本`],
  [`Release notes`, `发行说明`],
  [`Generate release notes`, `生成发行说明`],
  [`Open in github.dev`, `在 github.dev 中打开`],
  [`Open in GitHub Desktop`, `在 GitHub Desktop 中打开`],
  [`Open in Visual Studio Code`, `在 Visual Studio Code 中打开`],
  [`Codespaces`, `Codespaces`],
  [`Create codespace on main`, `在 main 上创建 codespace`],
  [`Stop codespace`, `停止 codespace`],
  [`Delete codespace`, `删除 codespace`],
  [`Open in browser`, `在浏览器中打开`],
  [`Manage codespaces`, `管理 codespaces`],
  [`Machine type`, `机器类型`],
  [`Idle timeout`, `空闲超时`],
  [`Forwarded ports`, `已转发端口`],
  [`Port visibility`, `端口可见性`],
  [`People`, `人员`],
  [`Teams`, `团队`],
  [`Members`, `成员`],
  [`Outside collaborators`, `外部协作者`],
  [`Invitations`, `邀请`],
  [`Pending invitations`, `待处理邀请`],
  [`Role`, `角色`],
  [`Owner`, `所有者`],
  [`Member`, `成员`],
  [`Billing`, `账单`],
  [`Licensing`, `许可`],
  [`Audit log`, `审计日志`],
  [`Moderation log`, `审核日志`],
  [`Repository rules`, `仓库规则`],
  [`Rulesets`, `规则集`],
  [`Rules`, `规则`],
  [`Archived repositories`, `已归档仓库`],
  [`Delete organization`, `删除组织`],
  [`Transfer repository`, `转移仓库`],
  [`Sponsors`, `赞助`],
  [`Sponsor`, `赞助`],
  [`Sponsor this project`, `赞助此项目`],
  [`Fund this project`, `资助此项目`],
  [`Used by`, `使用者`],
  [`Contributing`, `贡献指南`],
  [`Security policy`, `安全策略`],
  [`Code of conduct`, `行为准则`],
  [`Changelog`, `更新日志`],
  [`README`, `自述文件`],
  [`Trending`, `趋势`],
  [`Topics`, `主题`],
  [`Collections`, `合集`],
  [`No one assigned`, `无人分配`],
  [`Assignees`, `受理人`],
  [`Reviewers`, `审查者`],
  [`Sort by`, `排序方式`],
  [`Newest`, `最新`],
  [`Oldest`, `最早`],
  [`Most commented`, `评论最多`],
  [`Least commented`, `评论最少`],
  [`Recently updated`, `最近更新`],
  [`Least recently updated`, `最久未更新`],
  [`No results matched your search.`, `没有匹配你搜索的结果。`],
  [`Reset filters`, `重置筛选`],
  [`Create new issue`, `创建新问题`],
  [`Submit new issue`, `提交新问题`],
  [`Comment`, `评论`],
  [`Add a comment`, `添加评论`],
  [`Leave a comment`, `发表评论`],
  [`Comment body`, `评论内容`],
  [`Preview`, `预览`],
  [`Write`, `编写`],
  [`Submit`, `提交`],
  [`Close issue`, `关闭问题`],
  [`Reopen issue`, `重新打开问题`],
  [`Development`, `开发`],
  [`Linked pull requests`, `关联拉取请求`],
  [`No branches or pull requests`, `没有分支或拉取请求`],
  [`Create branch`, `创建分支`],
  [`Branch`, `分支`],
  [`Checks`, `检查`],
  [`Checks pending`, `检查等待中`],
  [`Checks failed`, `检查失败`],
  [`Code Search`, `代码搜索`],
  [`Search syntax tips`, `搜索语法提示`],
  [`Saved searches`, `已保存搜索`],
  [`Create saved search`, `创建已保存搜索`],
  [`Query`, `查询`],
  [`No saved searches`, `没有已保存搜索`],
  [`Clear`, `清除`],
  [`All`, `全部`],
  [`Open`, `开放`],
  [`Closed`, `已关闭`],
  [`Draft`, `草稿`],
  [`Merged`, `已合并`],
  [`Retry`, `重试`],
  [`Try again`, `重试`],
  [`Dismiss`, `关闭`],
  [`Expand`, `展开`],
  [`Collapse`, `折叠`],
  [`Show less`, `显示更少`],
  [`Details`, `详情`],
  [`Copy`, `复制`],
  [`Copied!`, `已复制！`],
  [`Update`, `更新`],
  [`Create`, `创建`],
  [`Submit`, `提交`],
  [`Continue`, `继续`],
  [`Back`, `返回`],
  [`Skip`, `跳过`],
  [`Optional`, `可选`],
  [`Required`, `必填`],
  [`Enabled`, `已启用`],
  [`Disabled`, `已禁用`],
  [`On`, `开启`],
  [`Off`, `关闭`],
  [`None`, `无`],
  [`Unknown`, `未知`],
  [`Loading…`, `加载中…`],
  [`Loading`, `加载中`],
  [`Change is constant. GitHub keeps you ahead.`, `变化不止，GitHub 让你始终领先。`],
  [`The future of building happens together`, `构建的未来因协作而生`],
  [
    `Tools and trends evolve, but collaboration endures. With GitHub, developers, agents, and code come together on one platform.`,
    `工具和趋势不断演进，但协作始终重要。在 GitHub 上，开发者、智能体与代码汇聚于同一平台。`,
  ],
  [`Enter your email`, `输入你的邮箱`],
  [`Sign up for GitHub`, `注册 GitHub`],
  [`Try GitHub Copilot free`, `免费试用 GitHub Copilot`],
  [`Your AI partner everywhere.`, `你无处不在的 AI 伙伴。`],
  [`Explore GitHub Copilot`, `探索 GitHub Copilot`],
  [`Automate your path to production`, `自动化你的生产交付路径`],
  [`Explore GitHub Actions`, `探索 GitHub Actions`],
  [`Code instantly from anywhere`, `随时随地即时编写代码`],
  [`Keep momentum on the go`, `随时保持开发节奏`],
  [`Shape your toolchain`, `打造你的工具链`],
  [
    `Apply fixes in seconds. Spend less time debugging and more time building features with Copilot Autofix.`,
    `秒级应用修复。借助 Copilot Autofix，减少调试时间，把精力投入到功能开发。`,
  ],
  [`Explore GitHub Advanced Security`, `探索 GitHub 高级安全`],
  [`Learn about GitHub Code Security`, `了解 GitHub 代码安全`],
  [`Learn about Dependabot`, `了解 Dependabot`],
  [`Learn about GitHub Secret Protection`, `了解 GitHub 机密保护`],
  [`Plan with clarity.`, `清晰规划。`],
  [`Explore GitHub Projects`, `探索 GitHub Projects`],
  [`Explore GitHub Issues`, `探索 GitHub Issues`],
  [`Terms`, `条款`],
  [`followers`, `关注者`],
  [`following`, `正在关注`],
  [`Code search`, `代码搜索`],
  [`Advanced Security`, `高级安全`],
  [`Code Security`, `代码安全`],
  [`Secret Protection`, `机密保护`],
  [`Code Review`, `代码审查`],
  [`Plans`, `计划`],
  [`Solutions`, `解决方案`],
  [`Resources`, `资源`],
  [`Open source`, `开源`],
  [`Enterprise`, `企业版`],
  [`Enterprise platform`, `企业平台`],
  [`By company size`, `按公司规模`],
  [`By use case`, `按使用场景`],
  [`By industry`, `按行业`],
  [`Customer stories`, `客户案例`],
  [`View all solutions`, `查看全部解决方案`],
  [`Read customer story`, `阅读客户案例`],
  [`Read industry report`, `阅读行业报告`],
  [`Try now`, `立即试用`],
  [`Start free trial`, `开始免费试用`],
  [`Start a free trial`, `开始免费试用`],
  [`Get started`, `开始使用`],
  [`Learn more about`, `了解更多`],
  [`See all`, `查看全部`],
  [`See all features`, `查看全部功能`],
  [`See all plans`, `查看全部计划`],
  [`See details`, `查看详情`],
  [`All features`, `全部功能`],
  [`Explore all`, `探索全部`],
  [`Collaborate`, `协作`],
  [`Automate`, `自动化`],
  [`Secure`, `安全`],
  [`Plan`, `规划`],
  [`Build and ship software on a single, collaborative platform`, `在统一协作平台上构建并交付软件`],
  [`Review code changes together`, `协作审查代码变更`],
  [`Share ideas and ask questions`, `分享想法并提出问题`],
  [`Keep track of your tasks`, `持续跟踪你的任务`],
  [`Fund open source projects`, `资助开源项目`],
  [`Code owners`, `代码所有者`],
  [`Code owners file`, `代码所有者文件`],
  [`Branch protection`, `分支保护`],
  [`Required status checks`, `必需状态检查`],
  [`Require a pull request before merging`, `合并前必须拉取请求`],
  [`Require approvals`, `需要批准`],
  [`Dismiss stale pull request approvals`, `自动撤销过期批准`],
  [`Require review from Code Owners`, `需要代码所有者审查`],
  [`Require conversation resolution before merging`, `合并前必须解决所有对话`],
  [`Allow force pushes`, `允许强制推送`],
  [`Allow deletions`, `允许删除`],
  [`Do not allow bypassing the above settings`, `不允许绕过上述设置`],
  [`Ruleset`, `规则集`],
  [`New ruleset`, `新建规则集`],
  [`Target branches`, `目标分支`],
  [`Enforcement status`, `执行状态`],
  [`Evaluate`, `评估`],
  [`Active`, `启用中`],
  [`Bypass list`, `绕过列表`],
  [`Repository role`, `仓库角色`],
  [`Bypass mode`, `绕过模式`],
  [`Push protection`, `推送保护`],
  [`Block pushes that contain secrets`, `阻止包含机密的推送`],
  [`Code scanning alerts`, `代码扫描警报`],
  [`Secret scanning alerts`, `机密扫描警报`],
  [`Security campaigns`, `安全活动`],
  [`Enable security features`, `启用安全功能`],
  [`Recommended security configuration`, `推荐安全配置`],
  [`Custom security configuration`, `自定义安全配置`],
  [`Dependabot`, `Dependabot`],
  [`Dependency review`, `依赖审查`],
  [`Dependency submission`, `依赖提交`],
  [`Dismiss alert`, `关闭警报`],
  [`Reopen alert`, `重新打开警报`],
  [`Dismissed`, `已关闭`],
  [`Open alert`, `打开警报`],
  [`Severity`, `严重性`],
  [`Critical`, `严重`],
  [`High`, `高`],
  [`Medium`, `中`],
  [`Low`, `低`],
  [`Primary language`, `主要语言`],
  [`Repository language`, `仓库语言`],
  [`Visibility`, `可见性`],
  [`Internal`, `内部`],
  [`Public repository`, `公开仓库`],
  [`Private repository`, `私有仓库`],
  [`Fork this repository`, `复刻此仓库`],
  [`Create fork`, `创建复刻`],
  [`Sync fork`, `同步复刻`],
  [`Contribute`, `贡献`],
  [`Compare`, `比较`],
  [`Fetch upstream`, `拉取上游`],
  [`Open pull request`, `打开拉取请求`],
  [`No description, website, or topics provided.`, `未提供描述、网站或主题。`],
  [`No releases published`, `未发布任何版本`],
  [`No discussions yet`, `暂无讨论`],
  [`No results`, `无结果`],
  [`Nothing to show`, `无内容可显示`],
  [`No items`, `无条目`],
  [`No assignees`, `无受理人`],
  [`No labels`, `无标签`],
  [`No reviewers`, `无审查者`],
  [`No projects`, `无项目`],
  [`No milestone`, `无里程碑`],
  [`Clear filters`, `清除筛选`],
  [`Filter by`, `按条件筛选`],
  [`Sort by recently updated`, `按最近更新排序`],
  [`Most reactions`, `最多反应`],
  [`Least reactions`, `最少反应`],
  [`Newest first`, `最新优先`],
  [`Oldest first`, `最早优先`],
  [`Add reaction`, `添加反应`],
  [`Add file comment`, `添加文件评论`],
  [`Start review`, `开始审查`],
  [`Pending review`, `待提交审查`],
  [`Viewed changes`, `已查看更改`],
  [`Review required`, `需要审查`],
  [`Merge queue`, `合并队列`],
  [`Added to merge queue`, `已加入合并队列`],
  [`Remove from queue`, `从队列移除`],
  [`Successfully merged`, `已成功合并`],
  [`Closed with unmerged commits`, `已关闭（未合并提交）`],
  [`Checks have passed`, `检查已通过`],
  [`Some checks were not successful`, `部分检查未成功`],
  [`Review required from`, `需要以下人员审查`],
  [`No conflicts with base branch`, `与基础分支无冲突`],
  [`This branch has conflicts`, `此分支存在冲突`],
  [`Able to merge`, `可合并`],
  [`Can’t automatically merge`, `无法自动合并`],
  [`Merging is blocked`, `合并被阻止`],
  [`Checks in progress`, `检查进行中`],
  [`Waiting for status to be reported`, `等待状态上报`],
  [`Projects (beta)`, `项目（测试版）`],
  [`Roadmap`, `路线图`],
  [`Board`, `看板`],
  [`Table`, `表格`],
  [`Iteration`, `迭代`],
  [`Iterations`, `迭代`],
  [`Fields`, `字段`],
  [`Add field`, `添加字段`],
  [`Add item`, `添加条目`],
  [`New item`, `新建条目`],
  [`Group by`, `分组方式`],
  [`Slice by`, `切分方式`],
  [`Layout`, `布局`],
  [`Workflow`, `工作流`],
  [`Insights`, `洞察`],
  [`Archive`, `归档`],
  [`Unarchive`, `取消归档`],
  [`Iteration field`, `迭代字段`],
  [`Start date`, `开始日期`],
  [`Target date`, `目标日期`],
  [`Due date`, `截止日期`],
  [`Sub-issues`, `子问题`],
  [`Tracked by`, `被跟踪于`],
  [`Tracks`, `跟踪`],
  [`Tracked issues`, `被跟踪问题`],
  [`Tasklist`, `任务清单`],
  [`Convert to issue`, `转换为问题`],
  [`Convert to discussion`, `转换为讨论`],
  [`Link issue`, `关联问题`],
  [`Unlink issue`, `取消关联问题`],
  [`Development links`, `开发关联`],
  [`Deployments`, `部署`],
  [`Environments`, `环境`],
  [`Production`, `生产环境`],
  [`Staging`, `预发布环境`],
  [`Queued deployments`, `排队部署`],
  [`Deployment history`, `部署历史`],
  [`Pages`, `Pages`],
  [`GitHub Pages`, `GitHub Pages`],
  [`Build and deployment`, `构建与部署`],
  [`Custom domain`, `自定义域名`],
  [`Source`, `来源`],
  [`Branch source`, `分支来源`],
  [`Save and publish`, `保存并发布`],
  [`Visit site`, `访问站点`],
  [`Workflow permissions`, `工作流权限`],
  [`Read repository contents permission`, `读取仓库内容权限`],
  [`Read and write permissions`, `读写权限`],
  [`Allow GitHub Actions to create and approve pull requests`, `允许 GitHub Actions 创建并批准拉取请求`],
  [`General settings`, `常规设置`],
  [`Access control`, `访问控制`],
  [`Manage access`, `管理访问`],
  [`Collaborator access`, `协作者访问`],
  [`Danger zone`, `危险区域`],
  [`Archive repository`, `归档仓库`],
  [`Unarchive repository`, `取消归档仓库`],
  [`Rename repository`, `重命名仓库`],
  [`Change default branch`, `更改默认分支`],
  [`Transfer ownership`, `转移所有权`],
  [`Delete repository`, `删除仓库`],
  [`Webhooks`, `Webhooks`],
  [`Add webhook`, `添加 Webhook`],
  [`Recent deliveries`, `最近投递`],
  [`Redeliver`, `重新投递`],
  [`Ping`, `Ping`],
  [`Deploy keys`, `部署密钥`],
  [`Add deploy key`, `添加部署密钥`],
  [`Read-only`, `只读`],
  [`Allow write access`, `允许写入权限`],
  [`Installed GitHub Apps`, `已安装 GitHub Apps`],
  [`Installed apps`, `已安装应用`],
  [`Configure`, `配置`],
  [`Suspend`, `暂停`],
  [`Unsuspend`, `恢复`],
  [`Remove`, `移除`],
  [`Notifications inbox`, `通知收件箱`],
  [`All notifications`, `全部通知`],
  [`Participating`, `参与中`],
  [`Done`, `已完成`],
  [`Mark as done`, `标记为已完成`],
  [`Mark as unread`, `标记为未读`],
  [`Mark all as read`, `全部标记为已读`],
  [`Unsubscribe`, `取消订阅`],
  [`Watch all activity`, `关注所有活动`],
  [`Custom`, `自定义`],
  [`Ignoring`, `忽略中`],
  [`Find file`, `查找文件`],
  [`Jump to line`, `跳转到行`],
  [`Open in`, `打开方式`],
  [`Open in new tab`, `在新标签页打开`],
  [`Open raw file`, `打开原始文件`],
  [`Download raw file`, `下载原始文件`],
  [`Raw file`, `原始文件`],
  [`Permalink copied`, `永久链接已复制`],
  [`Copied to clipboard`, `已复制到剪贴板`],
  [`Expand all`, `展开全部`],
  [`Collapse all`, `折叠全部`],
  [`Show all checks`, `显示全部检查`],
  [`Jump`, `跳转`],
  [`Search all of GitHub`, `搜索整个 GitHub`],
  [`Saved replies`, `已保存回复`],
  [`New saved reply`, `新建已保存回复`],
  [`Use saved reply`, `使用已保存回复`],
  [`Emojis`, `表情`],
  [`Attach files by dragging & dropping, selecting or pasting them.`, `可通过拖拽、选择或粘贴来附加文件。`],
  [`Quick search`, `快速搜索`],
  [`Command palette`, `命令面板`],
  [`Open command palette`, `打开命令面板`],
  [`Repository activity`, `仓库活动`],
  [`Pulse`, `脉搏`],
  [`Network`, `网络`],
  [`Forks`, `复刻`],
  [`Stars`, `星标`],
  [`Watchers`, `关注者`],
  [`Releases`, `版本`],
  [`Contributors`, `贡献者`],
  [`Packages`, `包`],
  [`Open issues`, `开放问题`],
  [`Open pull requests`, `开放拉取请求`],
  [`Last commit`, `最近提交`],
  [`Latest commit`, `最新提交`],
  [`Verified`, `已验证`],
  [`Unverified`, `未验证`],
  [`Verified signature`, `已验证签名`],
  [`Unverified signature`, `未验证签名`],
  [`Commit message`, `提交信息`],
  [`Commit details`, `提交详情`],
  [`Browse files`, `浏览文件`],
  [`Repository contents`, `仓库内容`],
  [`Changed files`, `更改的文件`],
  [`View changes`, `查看更改`],
  [`Search this repository`, `搜索此仓库`],
  [`Add topics`, `添加主题`],
  [`Edit topics`, `编辑主题`],
  [`Release`, `版本`],
  [`Latest release`, `最新版本`],
  [`Create release`, `创建版本`],
  [`Edit release`, `编辑版本`],
  [`Delete release`, `删除版本`],
  [`Publish release`, `发布版本`],
  [`Unpublish release`, `取消发布版本`],
  [`Compare tags`, `比较标签`],
  [`Reactions`, `反应`],
  [`Milestone`, `里程碑`],
  [`Linked issues`, `关联问题`],
  [`Linked issues and pull requests`, `关联问题和拉取请求`],
  [`Review requests`, `审查请求`],
  [`Requested reviewers`, `请求的审查者`],
  [`Requested teams`, `请求的团队`],
  [`Draft pull request`, `草稿拉取请求`],
  [`Convert draft to ready for review`, `将草稿转为可审查`],
  [`Mark pull request as ready for review`, `将拉取请求标记为可审查`],
  [`Edit title`, `编辑标题`],
  [`Edit body`, `编辑正文`],
  [`Comment and close`, `评论并关闭`],
  [`Comment and reopen`, `评论并重新打开`],
  [`Close with comment`, `评论并关闭`],
  [`Reopen with comment`, `评论并重新打开`],
  [`Edited`, `已编辑`],
  [`edited`, `已编辑`],
  [`yesterday`, `昨天`],
  [`today`, `今天`],
  [`just now`, `刚刚`],
  [`a minute ago`, `1 分钟前`],
  [`an hour ago`, `1 小时前`],
  [`a day ago`, `1 天前`],
  [`a week ago`, `1 周前`],
  [`a month ago`, `1 个月前`],
  [`a year ago`, `1 年前`],
  [`Platform`, `平台`],
  [`AI code creation`, `AI 代码创作`],
  [`Developer workflows`, `开发工作流`],
  [`Application security`, `应用安全`],
  [`Open source`, `开源`],
  [`Community`, `社区`],
  [`Why GitHub`, `为什么选择 GitHub`],
  [`Documentation`, `文档`],
  [`View all features`, `查看全部功能`],
  [`View all solutions`, `查看全部解决方案`],
  [`View all resources`, `查看全部资源`],
  [`View all use cases`, `查看全部使用场景`],
  [`View all industries`, `查看全部行业`],
  [`View all topics`, `查看全部主题`],
  [`GitHub Spark`, `GitHub Spark`],
  [`Build and deploy intelligent apps`, `构建并部署智能应用`],
  [`GitHub Models`, `GitHub Models`],
  [`Manage and compare prompts`, `管理并比较提示词`],
  [`MCP Registry`, `MCP 注册表`],
  [`Integrate external tools`, `集成外部工具`],
  [`Actions`, `Actions`],
  [`Automate any workflow`, `自动化任意工作流`],
  [`Codespaces`, `Codespaces`],
  [`Instant dev environments`, `即时开发环境`],
  [`Issues`, `Issues`],
  [`Plan and track work`, `规划并跟踪工作`],
  [`Manage code changes`, `管理代码变更`],
  [`Find and fix vulnerabilities`, `发现并修复漏洞`],
  [`Secure your code as you build`, `在开发过程中保护代码安全`],
  [`Stop leaks before they start`, `在泄露发生前阻止它`],
  [`By company size`, `按公司规模`],
  [`Enterprises`, `大型企业`],
  [`Small and medium teams`, `中小型团队`],
  [`Startups`, `初创公司`],
  [`Nonprofits`, `非营利组织`],
  [`App Modernization`, `应用现代化`],
  [`DevSecOps`, `DevSecOps`],
  [`DevOps`, `DevOps`],
  [`CI/CD`, `CI/CD`],
  [`Healthcare`, `医疗健康`],
  [`Financial services`, `金融服务`],
  [`Manufacturing`, `制造业`],
  [`Government`, `政府`],
  [`Explore by topic`, `按主题浏览`],
  [`Explore by type`, `按类型浏览`],
  [`Events & webinars`, `活动与网络研讨会`],
  [`Ebooks & reports`, `电子书与报告`],
  [`Business insights`, `商业洞察`],
  [`GitHub Skills`, `GitHub Skills`],
  [`Support & services`, `支持与服务`],
  [`Customer support`, `客户支持`],
  [`Community forum`, `社区论坛`],
  [`Trust center`, `信任中心`],
  [`Partners`, `合作伙伴`],
  [`Programs`, `项目计划`],
  [`Security Lab`, `安全实验室`],
  [`Maintainer Community`, `维护者社区`],
  [`Accelerator`, `加速器计划`],
  [`Archive Program`, `归档计划`],
  [`Enterprise solutions`, `企业解决方案`],
  [`Available add-ons`, `可选附加组件`],
  [`Enterprise platform`, `企业平台`],
  [`AI-powered developer platform`, `AI 驱动的开发者平台`],
  [`Copilot for Business`, `Copilot 企业版`],
  [`Premium Support`, `高级支持`],
  [`Enterprise-grade security features`, `企业级安全功能`],
  [`Enterprise-grade AI features`, `企业级 AI 功能`],
  [`Enterprise-grade 24/7 support`, `企业级 7x24 支持`],
  [`Search code, repositories, users, issues, pull requests...`, `搜索代码、仓库、用户、问题和拉取请求...`],
  [`Provide feedback`, `提供反馈`],
  [`We read every piece of feedback, and take your input very seriously.`, `我们会认真阅读每一条反馈，并高度重视你的意见。`],
  [`Include my email address so I can be contacted`, `附上我的邮箱地址以便联系我`],
  [`Submit feedback`, `提交反馈`],
  [`Use saved searches to filter your results more quickly`, `使用已保存搜索更快筛选结果`],
  [`To see all available qualifiers, see our documentation.`, `要查看所有可用限定符，请参阅我们的文档。`],
  [`Appearance settings`, `外观设置`],
  [`Resetting focus`, `正在重置焦点`],
  [`You signed in with another tab or window. Reload to refresh your session.`, `你已在另一个标签页或窗口中登录。重新加载以刷新当前会话。`],
  [`You signed out in another tab or window. Reload to refresh your session.`, `你已在另一个标签页或窗口中登出。重新加载以刷新当前会话。`],
  [`You switched accounts on another tab or window. Reload to refresh your session.`, `你已在另一个标签页或窗口中切换账号。重新加载以刷新当前会话。`],
  [`Dismiss alert`, `关闭提醒`],
  [`Open more actions menu`, `打开更多操作菜单`],
  [`Folders and files`, `文件夹和文件`],
  [`Last commit message`, `最近提交信息`],
  [`Last commit date`, `最近提交日期`],
  [`Repository files navigation`, `仓库文件导航`],
  [`About`, `关于`],
  [`Resources`, `资源`],
  [`License`, `许可证`],
  [`Uh oh!`, `糟糕！`],
  [`There was an error while loading. Please reload this page.`, `加载时出错。请重新加载此页面。`],
  [`watching`, `关注中`],
  [`forks`, `复刻`],
  [`Report repository`, `举报仓库`],
  [`No releases published`, `尚未发布任何版本`],
  [`No contributors`, `暂无贡献者`],
  [`Footer navigation`, `页脚导航`],
  [`Manage cookies`, `管理 Cookie`],
  [`Do not share my personal information`, `不要共享我的个人信息`],
  [`You can’t perform that action at this time.`, `你目前无法执行该操作。`],
  [`You can't perform that action at this time.`, `你目前无法执行该操作。`],
  [`Read/write`, `读写`],
  [`Read-only access`, `只读访问`],
  [`Admin`, `管理员`],
  [`Maintain`, `维护`],
  [`Triage`, `分诊`],
  [`Write access`, `写入权限`],
  [`Read access`, `读取权限`],
  [`Security policy`, `安全策略`],
  [`Code scanning results`, `代码扫描结果`],
  [`Secret scanning results`, `机密扫描结果`],
  [`Dependency insights`, `依赖洞察`],
  [`Copilot Autofix`, `Copilot Autofix`],
  [`GitHub Secret Protection`, `GitHub 机密保护`],
  [`Software Development`, `软件开发`],
  [`AI`, `AI`],
  [`Topic`, `主题`],
  [`Topics`, `主题`],
  [`Latest commit history`, `最近提交历史`],
  [`17 Commits`, `17 次提交`],
  [`Public preview`, `公开预览`],
  [`Preview`, `预览`],
  [`Repository`, `仓库`],
  [`Repositories`, `仓库`],
  [`People`, `人员`],
  [`Pinned repositories`, `置顶仓库`],
  [`Stars`, `星标`],
  [`Forks`, `复刻`],
  [`Watchers`, `关注者`],
  [`Updated`, `已更新`],
  [`Added`, `已添加`],
  [`Removed`, `已移除`],
  [`Joined`, `已加入`],
  [`Left`, `已离开`],
  [`Marketplace · Tools to improve your workflow · GitHub`, `Marketplace · 提升工作流效率的工具 · GitHub`],
  [`Menu`, `菜单`],
  [`Models for your every use case`, `适用于各种场景的模型`],
  [`Try, test, and deploy from a wide range of model types, sizes, and specializations.`, `从丰富的模型类型、规模和专长中进行试用、测试与部署。`],
  [`Model`, `模型`],
  [`App`, `应用`],
  [`Login to OpenCode through Github Copilot`, `通过 GitHub Copilot 登录 OpenCode`],
  [`Cut Code Review Time & Bugs in Half`, `将代码审查时间和缺陷减少一半`],
  [`Build, test, & deploy in a fast, consistent, and secure manner`, `以快速、一致且安全的方式构建、测试和部署`],
  [`Empowering developers to detect Security Vulnerabilities, Bugs, and Code Smells in pull requests and repositories`, `帮助开发者在拉取请求和仓库中发现安全漏洞、缺陷与代码异味`],
  [`Secrets Security Platform - The most downloaded GitHub app lets you find and fix hardcoded API keys in code`, `机密安全平台：下载量最高的 GitHub 应用可帮助你发现并修复代码中的硬编码 API 密钥`],
  [`View recommended or recent marketplace listings navigation`, `查看推荐或最近的 Marketplace 条目导航`],
  [`Automatic test report merging for all CI and languages into a single code coverage report directly into your pull request`, `将所有 CI 和语言的测试报告自动合并为单一覆盖率报告，并直接展示到拉取请求中`],
  [`Project management that's seamlessly integrated with GitHub’s data & interface, builds powerful insights & automates tasks`, `与 GitHub 数据和界面无缝集成的项目管理工具，可提供强大洞察并自动化任务`],
  [`Codacy helps to build effortless code quality and security for developers`, `Codacy 帮助开发者轻松提升代码质量与安全性`],
  [`Code quality and coverage done right`, `以正确方式完成代码质量与覆盖率管理`],
  [`Automated GitHub backups so you can recover fast, stay compliant, and never lose a line of code`, `自动化 GitHub 备份，让你快速恢复、保持合规，并且不丢失任何代码`],
  [`Continuously build, test, and deploy to any platform and cloud`, `持续构建、测试并部署到任意平台和云`],
  [`A GitHub app that optimizes your images`, `优化图像的 GitHub 应用`],
  [`Automated code review for humans and AI`, `面向人类与 AI 的自动化代码审查`],
  [`Automatically build, test, and deploy your project in minutes`, `在数分钟内自动构建、测试并部署你的项目`],
  [`An Agile project management tool that seamlessly integrates with GitHub Issues`, `与 GitHub Issues 无缝集成的敏捷项目管理工具`],
  [`Automated visual review platform`, `自动化可视化审查平台`],
  [`Manage your software localization collaboratively`, `协同管理你的软件本地化`],
  [`Real-time, cross-platform crash reporting and error logging`, `实时跨平台崩溃报告与错误日志`],
  [`Agile localization for your projects`, `适用于项目的敏捷本地化`],
  [`Ensure that new code is fully covered, and see coverage trends emerge. Works with any CI service`, `确保新代码得到完整覆盖，并查看覆盖率趋势。适用于任何 CI 服务`],
  [`Find accessibility issues in your pull requests`, `在拉取请求中发现无障碍问题`],
  [`Test Plan Driven QA Test Management for GitHub`, `面向 GitHub 的测试计划驱动 QA 测试管理`],
  [`Advanced static analysis for automatically finding runtime errors in JavaScript, TypeScript, React, and Vue code`, `用于自动发现 JavaScript、TypeScript、React 和 Vue 代码运行时错误的高级静态分析`],
  [`Repository search results · GitHub`, `仓库搜索结果 · GitHub`],
  [`More languages...`, `更多语言...`],
  [`Advanced`, `高级`],
  [`Number of followers`, `关注者数量`],
  [`Number of forks`, `复刻数量`],
  [`Number of stars`, `星标数量`],
  [`Date created`, `创建日期`],
  [`Date pushed`, `推送日期`],
  [`Archived`, `已归档`],
  [`results`, `结果`],
  [`Best match`, `最佳匹配`],
  [`View topic`, `查看主题`],
  [`Sponsor open source projects you depend on`, `赞助你所依赖的开源项目`],
  [`Contributors are working behind the scenes to make open source better for everyone—give them the help and recognition they deserve.`, `贡献者们正在幕后努力，让开源对所有人更好。请给予他们应得的帮助与认可。`],
  [`Explore sponsorable projects`, `探索可赞助项目`],
  [`ProTip!`, `提示！`],
  [`Press the`, `按下`],
  [`key to activate the search input again and adjust your query.`, `键以重新激活搜索输入框并调整查询。`],
  [`Explore GitHub · GitHub`, `探索 GitHub · GitHub`],
  [`Here's what's popular on GitHub today...`, `看看今天 GitHub 上的热门内容...`],
  [`Rubber Duck Thursdays`, `橡皮鸭星期四`],
  [`Hack on open source with us`, `和我们一起为开源项目编程`],
  [`Join us for Rubber Duck Thursdays! A lighthearted and informal stream where we work on some projects and do some live coding.`, `加入我们的“橡皮鸭星期四”吧！这是一个轻松随意的直播活动，我们会一起做项目并现场编写代码。`],
  [`Trending repository`, `趋势仓库`],
  [`Popular topic`, `热门主题`],
  [`Collection recommended by GitHub`, `GitHub 推荐合集`],
  [`This recommendation was created by GitHub staff`, `此推荐由 GitHub 团队创建`],
  [`See the 17 items in this collection`, `查看此合集中的 17 个条目`],
  [`Trending developers`, `趋势开发者`],
  [`See more trending developers`, `查看更多趋势开发者`],
  [`Github 汉化浏览器扩展. Contribute to googsql/githubCN development by creating an account on GitHub.`, `GitHub 汉化浏览器扩展。注册 GitHub 账号后可参与 googsql/githubCN 的开发。`],
  [`Latest commit History`, `最近提交历史`],
  [`Repository files navigation`, `仓库文件导航`],
  [`Readme`, `说明文档`],
  [`watching`, `关注中`],
  [`forks`, `复刻`],
  [`No packages published`, `尚未发布任何包`],
  [`Contributors0`, `贡献者 0`],
  [`Packages0`, `包 0`],
  [`GitHub Security · GitHub`, `GitHub 安全 · GitHub`],
  [`GitHub Security`, `GitHub 安全`],
  [`Powerful security, designed for developers`, `为开发者打造的强大安全能力`],
  [`Request a demo`, `申请演示`],
  [`See plans & pricing`, `查看方案与定价`],
  [`Get enterprise-grade, built-in application security.`, `获得企业级内建应用安全能力。`],
  [`Find out how platform security strengthens your workflow.`, `了解平台安全如何强化你的工作流。`],
  [`Read about platform security`, `了解平台安全`],
  [`Visit the Trust Center`, `访问信任中心`],
  [`Join the companies that secure their code with GitHub`, `加入使用 GitHub 保障代码安全的企业行列`],
  [`Prevent accidental secret exposure`, `防止机密意外泄露`],
  [`Push protection automatically blocks secrets before they reach your repository, keeping code clean without disrupting workflows.`, `推送保护会在机密进入仓库前自动拦截，在不打断工作流的前提下保持代码洁净。`],
  [`Find and fix vulnerabilities in your code`, `发现并修复代码中的漏洞`],
  [`Address security debt in your GitHub workflow with static analysis, AI remediation, and proactive vulnerability management.`, `通过静态分析、AI 修复和主动漏洞管理，在 GitHub 工作流中解决安全债务。`],
  [`Enhance your security strategy with the GitHub Security Lab`, `借助 GitHub 安全实验室强化你的安全策略`],
  [`Learn how the lab helps secure open source by finding vulnerabilities, building tools like CodeQL, and advancing security research.`, `了解实验室如何通过发现漏洞、构建 CodeQL 等工具以及推进安全研究来保护开源生态。`],
  [`Visit the GitHub Security Lab`, `访问 GitHub 安全实验室`],
  [`Stay ahead of threats with the Security Advisory Database`, `借助安全通告数据库抢先应对威胁`],
  [`Access a security vulnerability database inclusive of CVEs and GitHub originated security advisories from the world of open source software.`, `访问涵盖 CVE 和 GitHub 原生安全通告的安全漏洞数据库，覆盖整个开源软件世界。`],
  [`Visit the GitHub Security Database`, `访问 GitHub 安全数据库`],
  [`GitHub’s supply chain security reduces open source risks with auto-updates, dependency tracking, and build attestation.`, `GitHub 的供应链安全通过自动更新、依赖跟踪和构建证明来降低开源风险。`],
  [`Learn more about supply chain security`, `了解更多供应链安全`],
  [`Built-in security for developer workflows`, `面向开发者工作流的内建安全`],
  [`Discover developer-first security`, `探索开发者优先的安全能力`],
  [`Take an in-depth look at the current state of application security.`, `深入了解当前应用安全的现状。`],
  [`View the webinar`, `查看网络研讨会`],
  [`Explore the DevSecOps guide`, `探索 DevSecOps 指南`],
  [`Learn how to write more secure code from the start with DevSecOps.`, `了解如何借助 DevSecOps 从一开始就编写更安全的代码。`],
  [`Read the whitepaper`, `阅读白皮书`],
  [`Avoid AppSec pitfalls`, `避免应用安全陷阱`],
  [`Explore common application security pitfalls and how to avoid them.`, `探索常见的应用安全陷阱以及规避方法。`],
  [`Trending repositories on GitHub today · GitHub`, `今日 GitHub 趋势仓库 · GitHub`],
  [`Trending`, `趋势`],
  [`See what the GitHub community is most excited about today.`, `看看今天 GitHub 社区最关注的内容。`],
  [`Spoken Language: Any`, `口语语言：任意`],
  [`Select a spoken language`, `选择口语语言`],
  [`Language: Any`, `编程语言：任意`],
  [`Select a language`, `选择语言`],
  [`Unknown languages`, `未知语言`],
  [`Date range: Today`, `时间范围：今天`],
  [`Adjust time span`, `调整时间范围`],
  [`Today`, `今天`],
  [`This week`, `本周`],
  [`This month`, `本月`],
  [`Built by`, `今日新增`],
  [`stars today`, `星标`],
  [`Official, Anthropic-managed directory of high quality Claude Code Plugins.`, `由 Anthropic 官方维护的高质量 Claude Code 插件目录。`],
  [`Fully automatic censorship removal for language models`, `面向语言模型的全自动审查限制移除工具`],
  [`SOTA Open Source TTS`, `最先进的开源 TTS`],
  [`An agentic skills framework & software development methodology that works.`, `一套真正有效的智能体技能框架与软件开发方法论。`],
  [`A complete AI agency at your fingertips - From frontend wizards to Reddit community ninjas, from whimsy injectors to reality checkers. Each agent is a specialized expert with personality, processes, and proven deliverables.`, `一整套 AI 智能体团队尽在指尖，从前端高手到社区运营专家，从创意注入者到现实校验者。每个智能体都是具备个性、流程与成熟交付能力的专业专家。`],
];
const normalizeText = (text) =>
  text
    .replace(/\u2026/g, "...")
    .replace(/[’‘]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/\s+/g, " ")
    .trim();
const exactDataMap = new Map();
const lowercaseDataMap = new Map();
const inlineReplacePairs = [];
const attrList = [
  "data-label",
  "placeholder",
  "value",
  "data-signin-label",
  "data-disable-with",
  "aria-label",
  "aria-placeholder",
  "aria-description",
  "aria-valuetext",
  "title",
];
const skipTagNames = new Set([
  "SCRIPT",
  "STYLE",
  "NOSCRIPT",
  "CODE",
  "PRE",
  "TEXTAREA",
]);

allData.forEach(([key, val]) => {
  if (!key || !val) return;
  const normalizedKey = normalizeText(key);
  if (!normalizedKey) return;
  if (normalizedKey.length <= 1) return;
  exactDataMap.set(normalizedKey, val);
  const lowercaseKey = normalizedKey.toLowerCase();
  lowercaseDataMap.set(lowercaseKey, val);
  if (
    normalizedKey.length >= 8 &&
    normalizedKey.includes(" ") &&
    normalizedKey !== val
  ) {
    inlineReplacePairs.push([normalizedKey, val]);
  }
});
inlineReplacePairs.sort((a, b) => b[0].length - a[0].length);

const patternReplacers = [
  [/^(\d+)\s+seconds?\s+ago$/i, (m) => `${m[1]} 秒前`],
  [/^(\d+)\s+minutes?\s+ago$/i, (m) => `${m[1]} 分钟前`],
  [/^(\d+)\s+hours?\s+ago$/i, (m) => `${m[1]} 小时前`],
  [/^(\d+)\s+days?\s+ago$/i, (m) => `${m[1]} 天前`],
  [/^(\d+)\s+weeks?\s+ago$/i, (m) => `${m[1]} 周前`],
  [/^(\d+)\s+months?\s+ago$/i, (m) => `${m[1]} 个月前`],
  [/^(\d+)\s+years?\s+ago$/i, (m) => `${m[1]} 年前`],
  [/^(\d+)\s+commits?$/i, (m) => `${m[1]} 次提交`],
  [/^(\d+)\s+contributors?$/i, (m) => `${m[1]} 位贡献者`],
  [/^(\d+)\s+releases?$/i, (m) => `${m[1]} 个版本`],
  [/^(\d+)\s+packages?$/i, (m) => `${m[1]} 个包`],
  [/^(\d+)\s+issues?$/i, (m) => `${m[1]} 个问题`],
  [/^(\d+)\s+pull requests?$/i, (m) => `${m[1]} 个拉取请求`],
  [/^(\d+)\s+forks?$/i, (m) => `${m[1]} 次复刻`],
  [/^(\d+)\s+stars?$/i, (m) => `${m[1]} 颗星`],
  [/^(\d+)\s+watchers?$/i, (m) => `${m[1]} 位关注者`],
  [/^updated\s+(\d+)\s+seconds?\s+ago$/i, (m) => `${m[1]} 秒前更新`],
  [/^updated\s+(\d+)\s+minutes?\s+ago$/i, (m) => `${m[1]} 分钟前更新`],
  [/^updated\s+(\d+)\s+hours?\s+ago$/i, (m) => `${m[1]} 小时前更新`],
  [/^updated\s+(\d+)\s+days?\s+ago$/i, (m) => `${m[1]} 天前更新`],
  [/^updated\s+(\d+)\s+weeks?\s+ago$/i, (m) => `${m[1]} 周前更新`],
  [/^updated\s+(\d+)\s+months?\s+ago$/i, (m) => `${m[1]} 个月前更新`],
  [/^updated\s+(\d+)\s+years?\s+ago$/i, (m) => `${m[1]} 年前更新`],
  [/^(\d+)\s+comments?$/i, (m) => `${m[1]} 条评论`],
  [/^(\d+)\s+reviews?$/i, (m) => `${m[1]} 条审查`],
  [/^(\d+)\s+checks?$/i, (m) => `${m[1]} 项检查`],
  [/^(\d+)\s+files?\s+changed$/i, (m) => `${m[1]} 个文件已更改`],
  [/^(\d+)\s+additions?$/i, (m) => `${m[1]} 处新增`],
  [/^(\d+)\s+deletions?$/i, (m) => `${m[1]} 处删除`],
  [/^Built by\s+([\d,]+)\s+stars?\s+today$/i, (m) => `今日新增 ${m[1]} 星标`],
  [/^Updated\s+([A-Z][a-z]{2}\s+\d{1,2},\s+\d{4})$/i, (m) => `更新于 ${m[1]}`],
  [
    /^(\d+)\s+changed files?\s+with\s+(\d+)\s+additions?\s+and\s+(\d+)\s+deletions?$/i,
    (m) => `${m[1]} 个文件变更，新增 ${m[2]} 处，删除 ${m[3]} 处`,
  ],
  [/^opened\s+(\d+)\s+days?\s+ago\s+by\s+(.+)$/i, (m) => `${m[2]} 于 ${m[1]} 天前创建`],
  [
    /^opened\s+(\d+)\s+hours?\s+ago\s+by\s+(.+)$/i,
    (m) => `${m[2]} 于 ${m[1]} 小时前创建`,
  ],
  [
    /^opened\s+(\d+)\s+minutes?\s+ago\s+by\s+(.+)$/i,
    (m) => `${m[2]} 于 ${m[1]} 分钟前创建`,
  ],
  [/^by\s+(.+)$/i, (m) => `由 ${m[1]}`],
];

const translateInSentence = (rawText) => {
  if (!rawText.includes(" ")) return null;
  let replaced = rawText;
  let changed = false;
  for (const [source, target] of inlineReplacePairs) {
    if (replaced.includes(source)) {
      replaced = replaced.split(source).join(target);
      changed = true;
    }
  }
  return changed ? replaced : null;
};

const translateCoreText = (rawText) => {
  const key = normalizeText(rawText);
  if (!key) return null;
  const exact = exactDataMap.get(key);
  if (exact) return exact;
  const lower = lowercaseDataMap.get(key.toLowerCase());
  if (lower) return lower;
  for (const [regex, replacer] of patternReplacers) {
    const match = key.match(regex);
    if (match) return replacer(match);
  }
  const inlineTranslated = translateInSentence(key);
  if (inlineTranslated && inlineTranslated !== key) return inlineTranslated;
  return null;
};

const shouldTranslateValueAttr = (element) => {
  if (!element || !element.tagName) return false;
  if (element.tagName === "BUTTON") return true;
  if (element.tagName !== "INPUT") return false;
  const type = (element.getAttribute("type") || "").toLowerCase();
  return type === "button" || type === "submit" || type === "reset";
};

const translateAttribute = (element, attr) => {
  if (!element.hasAttribute(attr)) return;
  if (attr === "value" && !shouldTranslateValueAttr(element)) return;
  const origin = element.getAttribute(attr);
  if (!origin) return;
  const translated = translateCoreText(origin);
  if (translated && translated !== origin) {
    element.setAttribute(attr, translated);
  }
};

const translateTextNode = (node) => {
  if (!node || node.nodeType !== Node.TEXT_NODE) return;
  const originalText = node.textContent || "";
  if (!originalText.trim()) return;
  if (
    node.parentElement &&
    node.parentElement.tagName &&
    skipTagNames.has(node.parentElement.tagName)
  ) {
    return;
  }
  const match = originalText.match(/^(\s*)([\s\S]*?)(\s*)$/);
  if (!match) return;
  const translated = translateCoreText(match[2]);
  if (!translated || translated === match[2]) return;
  node.textContent = `${match[1]}${translated}${match[3]}`;
};

const translateElement = (element) => {
  if (!element || element.nodeType !== Node.ELEMENT_NODE) return;
  if (skipTagNames.has(element.tagName)) return;
  attrList.forEach((attr) => translateAttribute(element, attr));
};

const processNodeTree = (rootNode) => {
  if (!rootNode) return;
  if (rootNode.nodeType === Node.TEXT_NODE) {
    translateTextNode(rootNode);
    return;
  }
  if (rootNode.nodeType !== Node.ELEMENT_NODE) return;
  const walker = document.createTreeWalker(rootNode, NodeFilter.SHOW_ALL);
  let currentNode = walker.currentNode;
  while (currentNode) {
    if (currentNode.nodeType === Node.TEXT_NODE) {
      translateTextNode(currentNode);
    } else if (currentNode.nodeType === Node.ELEMENT_NODE) {
      translateElement(currentNode);
    }
    currentNode = walker.nextNode();
  }
};

const MutationObserverConfig = {
  childList: true,
  subtree: true,
  characterData: true,
  attributes: true,
  attributeFilter: attrList,
};

processNodeTree(document.body);

const observer = new MutationObserver((mutations) => {
  mutations.forEach((mutation) => {
    if (mutation.type === "characterData") {
      translateTextNode(mutation.target);
      return;
    }
    if (mutation.type === "attributes" && mutation.target) {
      translateElement(mutation.target);
      return;
    }
    if (mutation.type === "childList" && mutation.addedNodes.length > 0) {
      mutation.addedNodes.forEach((node) => processNodeTree(node));
    }
  });
});

observer.observe(document.body, MutationObserverConfig);
